name: release

on:
  push:
    branches: main # main 分支提交时触发

jobs:
  deploy:
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Use Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Install Dependencies
        run: npm install

      - build: Build
        run: npm run build:prod

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 # 使用 SFTP 协议上传到服务器
        with:
          username: 'root'
          server: '${{ secrets.SERVER_HOST }}'
          ssh_private_key: '${{ secrets.ACCESS_TOKEN }}'
          local_path: './dist/*'
          remote_path: '/home/webroot/family-tree-front/'
          args: "-o ConnectTimeout=5"
