name: release

on:
  push:
    branches: main # main 分支提交时触发

# 取消正在进行中的工作流
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: Code style lint
        run: npm run lint

      - name: Build
        run: npm run build:prod

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4 # 使用 SFTP 协议上传到服务器
        with:
          username: 'root'
          server: '${{ secrets.SERVER_HOST }}'
          ssh_private_key: '${{ secrets.ACCESS_TOKEN }}'
          local_path: './dist/*'
          remote_path: '/home/webroot/family-tree-front/'
